version: "3"

tasks:
  generate-auth:
    aliases:
      - auth
    desc: "command to generate auth gRPC-server and gRPC-client using protofiles"
    cmds:
      - protoc -I proto ./proto/auth.proto --go_out=./gen/go/auth --go_opt=paths=source_relative --go-grpc_out=./gen/go/auth --go-grpc_opt=paths=source_relative
  
  generate-userinfo:
    aliases:
      - userinfo
    desc: "command to generate userinfo gRPC-server and gRPC-client using protofiles"
    cmds:
      - protoc -I proto ./proto/userinfo.proto --go_out=./gen/go/userinfo --go_opt=paths=source_relative --go-grpc_out=./gen/go/userinfo --go-grpc_opt=paths=source_relative
  
  generate-follow:
    aliases:
      - follow
    desc: "command to generate follow service gRPC-server and gRPC-client using protofiles"
    cmds:
      - protoc -I proto ./proto/follow.proto --go_out=./gen/go/follow --go_opt=paths=source_relative --go-grpc_out=./gen/go/follow --go-grpc_opt=paths=source_relative

  default:
    cmds:
      - task auth | task userinfo | task follow